# Generated by Django 5.2.6 on 2025-09-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='criado_em',
            new_name='criada_em',
        ),
    ]
